version: "3.9"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    network_mode: bridge
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /host/app/config/tdarr/server:/app/server
      - /host/app/config/tdarr/configs:/app/configs
      - /host/app/config/tdarr/logs:/app/logs
      - /host/data/media:/media
      - /host/data/tdarr/temp:/temp # Transcode cache
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    restart: unless-stopped

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    

  # node example
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    network_mode: service:tdarr
    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1000
      - nodeName=MyExternalNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /host/app/config/tdarr/configs:/app/configs
      - /host/app/config/tdarr/logs:/app/logs
      - /host/data/media:/media
      - /host/data/tdarr/temp:/temp # Transcode cache
    restart: unless-stopped

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]