version: "3.9"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /host/app/config/lidarr:/config
      - /host/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped