version: "3.9"
services:
  filebrowser:
    image: khairul169/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8000:80"  # Browser UI port
    volumes:
      - /host/app/config/filebrowser:/config  # Persistent config
      - /host/data:/srv/data  # Mount directory to track
    environment:
      # - FB_BASEURL=/  # Optional: For reverse proxy setups
      # - FB_USERNAME=admin  # Set custom admin username
      # - FB_PASSWORD=changeme  # Set strong password
      - TZ=Etc/UTC