version: "3.9"
services:
  # Prowlarr (outside VPN, manages indexers)
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/app/prowlarr:/config
    ports:
      - "9696:9696"  # Prowlarr WebUI
    restart: unless-stopped

  # Radarr (outside VPN, manages movies)
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/app/radarr:/config       # Radarr config files
      - ~/downloads:/downloads     # Must match qBittorrent's download path
      - ~/media/movies:/movies     # Final library location (adjust if needed)
    ports:
      - "7878:7878"  # Radarr Web UI (now on host network)
    restart: unless-stopped

  # Sonarr (outside VPN, manages series)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/app/sonarr:/config
      - ~/media/series:/tv #optional
      - ~/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  # Bazarr (outside VPN, manages subtitles)
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/app/bazarr:/config
      - ~/media/movies:/movies #optional
      - ~/media/series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  # Overseerr (outside VPN, manages requests)
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  # Autoscan (monitors file system changes and triggers library scans)
  # autoscan:
  #   image: cloudb0x/autoscan:latest
  #   container_name: autoscan
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC 
  #     # Optional: Set verbosity (0 = info, 1 = debug, 2 = trace)
  #     - AUTOSCAN_VERBOSITY=0
  #   volumes:
  #     - ~/app/autoscan:/config  # Autoscan configuration files
  #     - ~/media:/media:ro  # Read-only access to your media
  #   ports:
  #     - "3030:3030"  # Autoscan webhook port
  #   restart: unless-stopped

  # Organizr (outside VPN, manages services)
  # organizr:
  #   image: linuxserver/organizr
  #   container_name: organizr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ~/app/organizr:/config
  #   ports:
  #     - 9983:80
  #   restart: unless-stopped
