version: "3.9"
services:
  nordlynx:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordlynx
    ports:
        - "8080:8080" # port I want forwarded for the qbittorrent container
        - "6881:6881" # port I want forwarded for the qbittorrent container
        # - "6881:6881/udp" # port I want forwarded for the qbittorrent container
    cap_add:
      - NET_ADMIN #required
    environment:
      - PRIVATE_KEY_FILE=/run/secrets/privatekey
      # Define your local network that should bypass the VPN (adjust to your LAN)
      - NET_LOCAL=192.168.2.0/24,100.64.0.0/10
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    secrets:
      - privatekey
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /host/app/config/qbittorrent:/config
      - /host/data/torrents:/data/torrents #optional
    # ports:
    #   - 8080:8080
    #   - 6881:6881
    #   - 6881:6881/udp
    network_mode: service:nordlynx
    depends_on:
        - nordlynx
    restart: unless-stopped

secrets:
  privatekey:
    file: /host/app/secrets/nordlynx_privatekey.txt
