version: "3.9"
services:
  # Duplicati for backups
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SETTINGS_ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ${HOME}/app/config/duplicati:/config  # Duplicati's own configuration
      - ${HOME}/app/config:/source/app        # All *arr configs
      # Explicitly exclude media directories by not mounting them
    ports:
      - "8200:8200"  # Web UI port
    restart: unless-stopped